### ISSUE TITLE
Vagrant Package is not supported?

### ISSUE THREAD

**Issue by zmingxie** [ppggff/vagrant-qemu#4]
Hello! 

I just give it a try, and it works pretty well. The only issue I've found so far is it doesn't support the `package` command:
```
DEBUG command: Packaging VM: default
 INFO machine: Calling action: package on provider QEMU (VZKGb7Fgz-I)
DEBUG environment: Attempting to acquire process-lock: machine-action-0fe12d35dde59fdd50f349c52d5c59db
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-0fe12d35dde59fdd50f349c52d5c59db
 INFO interface: Machine: action ["package", "start", {:target=>:default}]
 INFO runner: Running action: machine_action_package #<Proc:0x00007f7b2a84ac18 /Users/zmingxie/.vagrant.d/gems/2.7.4/gems/vagrant-qemu-0.1.7/lib/vagrant-qemu/action.rb:12 (lambda)>
 INFO warden: Calling IN action: #<Proc:0x00007f7b492b7340 /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:126 (lambda)>
ERROR warden: Error occurred: Function not supported.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-0fe12d35dde59fdd50f349c52d5c59db
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007f7b2a928658>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::QEMU::Errors::NotSupportedError: Function not supported.>
ERROR vagrant: Function not supported.
ERROR vagrant: /Users/zmingxie/.vagrant.d/gems/2.7.4/gems/vagrant-qemu-0.1.7/lib/vagrant-qemu/action.rb:13:in `block in action_package'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/package/command.rb:94:in `package_vm'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/package/command.rb:83:in `block in package_target'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:232:in `each'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/package/command.rb:81:in `package_target'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/package/command.rb:49:in `execute'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/cli.rb:67:in `execute'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:290:in `cli'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:231:in `<main>'
 INFO interface: error: Function not supported.
Function not supported.
 INFO interface: Machine: error-exit ["VagrantPlugins::QEMU::Errors::NotSupportedError", "Function not supported."]
```

Are you planning to add this soon?

Thanks again for putting this plugin together!

**Comment by ppggff** [comment]
Yes, the next goal is 'package'.
