### ISSUE TITLE
How to setup private network

### ISSUE THREAD

**Issue by Agus-Wei** [ppggff/vagrant-qemu#40]
Is it possible to setup private network through Vagrantfile?

**Comment by leifliddy** [comment]
There's been a couple issues created on this topic.
https://github.com/ppggff/vagrant-qemu/issues/33

**Comment by unixerius** [comment]
@andronat , @ppggff already said this plugin hasn't been adjusted to work with vmnet-* yet. 

Like you, I would love to use these solutions, but it's not possible yet.

**Comment by unixerius** [comment]
With regards to [your post of May 8th](https://github.com/ppggff/vagrant-qemu/issues/40#issuecomment-1537665609), I feel that you should wait for Qemu to build in the required support for non-privileged users. 

They themselves have already identified that their biggest hurdle is that their software isn't flagged by Apple as being permitted to use the `com.apple.vm.networking` entitlement. The main reason for this is A) that they haven't requested it and B) that their `brew install` does a build from source code. [source](https://gitlab.com/qemu-project/qemu/-/issues/1364#note_1220859005)

That seems like something they as project should be able to work on. Until they've done so, I would not recommend that you build in a `sudo` workaround.

**Comment by ppggff** [comment]
See [pr#73](https://github.com/ppggff/vagrant-qemu/pull/73) for an example that use socket_vmnet to communicate between machines.

**Comment by ppggff** [comment]
**v0.4.0** (now on RubyGems) adds `private_network` support behind an opt-in `advanced_network = true`. It creates a dual-NIC setup — NIC 0 user-mode (SSH + port forwarding), NIC 1 a platform backend (vmnet on macOS, TAP on Linux, or the QEMU `socket` netdev) — and delivers the static IP via a cloud-init NoCloud seed (so the guest box needs cloud-init). Without `advanced_network` the provider now warns instead of silently ignoring the config.

```ruby
config.vm.network "private_network", ip: "192.168.105.10"
config.vm.provider "qemu" do |qe|
  qe.advanced_network = true
  # qe.net_mode = :vmnet_shared   # macOS default; needs `sudo vagrant up`
end
```

See the "Advanced networking" section of the README for the backends and a no-root macOS option (`socket` listen/connect).

```sh
vagrant plugin install vagrant-qemu
```
Please give it a try and let me know!

**Comment by ronjakoi** [comment]
> config.vm.network "private_network", ip: "192.168.105.10"
> config.vm.provider "qemu" do |qe|
>   qe.advanced_network = true
>   # qe.net_mode = :vmnet_shared   # macOS default; needs `sudo vagrant up`
> end
> See the "Advanced networking" section of the README for the backends and a no-root macOS option (`socket` listen/connect).
> 
> vagrant plugin install vagrant-qemu
> Please give it a try and let me know!

This crashes for me:

```
/Users/ronja/.vagrant.d/gems/3.3.8/gems/vagrant-qemu-0.6.2/lib/vagrant-qemu/driver.rb:145:in `+': no implicit conversion of nil into Array (TypeError)

              cmd += backend.build_netdev_args("net1", options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/ronja/.vagrant.d/gems/3.3.8/gems/vagrant-qemu-0.6.2/lib/vagrant-qemu/driver.rb:145:in `start'
	from /Users/ronja/.vagrant.d/gems/3.3.8/gems/vagrant-qemu-0.6.2/lib/vagrant-qemu/action/start_instance.rb:62:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/set_hostname.rb:20:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /Users/ronja/.vagrant.d/gems/3.3.8/gems/vagrant-qemu-0.6.2/lib/vagrant-qemu/action/warn_networks.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/synced_folders.rb:90:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/delayed.rb:22:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/synced_folder_cleanup.rb:31:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/plugins/synced_folders/nfs/action_cleanup.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:54:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /Users/ronja/.vagrant.d/gems/3.3.8/gems/vagrant-qemu-0.6.2/lib/vagrant-qemu/action/prepare_forwarded_port_collision_params.rb:43:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/env_set.rb:22:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/provision.rb:83:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/disk.rb:36:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/cleanup_disks.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /Users/ronja/.vagrant.d/gems/3.3.8/gems/vagrant-qemu-0.6.2/lib/vagrant-qemu/action/cloud_init_network.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/cloud_init_setup.rb:54:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builder.rb:183:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/runner.rb:104:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/util/busy.rb:22:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/runner.rb:104:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/call.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:117:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builder.rb:183:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/runner.rb:104:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/util/busy.rb:22:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/runner.rb:104:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/call.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/box_check_outdated.rb:98:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/config_validate.rb:28:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builtin/handle_box.rb:58:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/builder.rb:183:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/runner.rb:104:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/util/busy.rb:22:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/action/runner.rb:104:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/machine.rb:244:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/machine.rb:213:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/environment.rb:647:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/machine.rb:199:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/machine.rb:199:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/lib/vagrant/batch_action.rb:88:in `block (2 levels) in run'
```

```
% vagrant --version
Vagrant 2.4.9
% vagrant plugin list
vagrant-qemu (0.6.2, global)
```

Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "qemu" do |qe|
    # qe.smp = "cpus=2,sockets=1,cores=2,threads=1"
    qe.advanced_network = true
    # qe.memory = "2048"
  end
end
```

**Comment by ppggff** [comment]
Fixed in 0.6.3, just released. This was a plugin bug: `net_mode` defaults to `:auto`, which selects the vmnet backend on macOS but was never resolved to a concrete mode, so the backend produced no netdev arguments and the command line assembly hit that `TypeError`.

```
vagrant plugin update vagrant-qemu
```

Your Vagrantfile should work as-is now. One thing to know: the default backend on macOS is vmnet-shared, which needs root, so it's `sudo vagrant up`. To avoid sudo, use `qe.net_mode = :socket_vmnet` instead — that needs the [socket_vmnet](https://github.com/lima-vm/socket_vmnet) daemon, and its subnet is set by the daemon (default `192.168.105.0/24`), so the static IP has to fall inside that range.

Thanks for the report.
