### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by 825i** [ppggff/vagrant-qemu#9]
When trying to install the plugin on my M1 Mac I get this error:

```
➜  vagrant vagrant plugin install vagrant-qemu
Installing the 'vagrant-qemu' plugin. This can take a few minutes...
Traceback (most recent call last):
	38: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:231:in `<main>'
	37: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:290:in `cli'
	36: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/cli.rb:67:in `execute'
	35: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/plugin/command/root.rb:66:in `execute'
	34: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/plugin/command/install.rb:69:in `execute'
	33: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/plugin/command/install.rb:69:in `each'
	32: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	31: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/plugin/command/base.rb:14:in `action'
	30: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	29: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	28: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	27: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	26: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	25: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/plugin/action/install_gem.rb:30:in `call'
	24: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	23: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	22: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/bundler.rb:350:in `install'
	21: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/bundler.rb:606:in `internal_install'
	20: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/request_set.rb:283:in `install_into'
	19: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/request_set.rb:283:in `each'
	18: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/request_set.rb:291:in `block in install_into'
	17: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/resolver/specification.rb:93:in `install'
	16: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/installer.rb:325:in `install'
	15: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/installer.rb:865:in `extract_files'
	14: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:394:in `extract_files'
	13: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package/file_source.rb:30:in `with_read_io'
	12: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package/file_source.rb:30:in `open'
	11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:397:in `block in extract_files'
	10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package/tar_reader.rb:67:in `each'
	 9: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:400:in `block (2 levels) in extract_files'
	 8: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:420:in `extract_tar_gz'
	 7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:547:in `open_tar_gz'
	 6: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:547:in `wrap'
	 5: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:550:in `block in open_tar_gz'
	 4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:421:in `block in extract_tar_gz'
	 3: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package/tar_reader.rb:67:in `each'
	 2: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:440:in `block (2 levels) in extract_tar_gz'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:440:in `open'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/package.rb:440:in `initialize': Permission denied @ rb_sysopen - /Users/adminuser/.vagrant.d/gems/2.7.4/gems/vagrant-qemu-0.1.8/.gitignore (Errno::EACCES)
➜  vagrant 
```

I shouldn't have to run this as superuser to install, so is there a problem with the plugin?

**Comment by ppggff** [comment]
Who is the user running vagrant?

It seems this user doesn't have the permission to use `/Users/adminuser/.vagrant.d/gems/2.7.4/gems/vagrant-qemu-0.1.8/.gitignore`.
